vich_uploader:
    db_driver: orm

    mappings:
        realisation_image:
            uri_prefix: /assets/images/realisations
            upload_destination: '%kernel.project_dir%/public/assets/images/realisations'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
